### ISSUE TITLE
Hi,when I train the model,there will be a problem such as Failed to establish a new connection,please tell me what should I do.Thank you!

### ISSUE THREAD

**Issue by Ykw1234** [James-Yip/AttentionImageClass#11]
------------------------------------------------------------
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\urllib3\connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "D:\anaconda\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "D:\anaconda\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by mymuli** [comment]
注释visdom相关代码...利用print输出相关的评价指标就可以
